In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
RAW_DATA_PATH = "data"

sales2017 = pd.read_csv(os.path.join(RAW_DATA_PATH, "Sales 2017.csv"))
sales2018 = pd.read_csv(os.path.join(RAW_DATA_PATH, "Sales 2018.csv"))
customers = pd.read_csv(os.path.join(RAW_DATA_PATH, "Customers.csv"))
products  = pd.read_csv(os.path.join(RAW_DATA_PATH, "Products.csv"))
regions   = pd.read_csv(os.path.join(RAW_DATA_PATH, "Region.csv"))
returns   = pd.read_csv(os.path.join(RAW_DATA_PATH, "Returns.csv"))
stores    = pd.read_csv(os.path.join(RAW_DATA_PATH, "Stores.csv"))

In [3]:
tables = {
    "sales2017" : sales2017,
    "sales2018" : sales2018,
    "customers" : customers,
    "products" : products,
    "regions" : regions,
    "returns" : returns,
    "stores" : stores
}

In [4]:
for key, df in tables.items():
    print(f"\t\t**{key}**")
    print(pd.DataFrame(df).head())

		**sales2017**
  transaction_date  stock_date  product_id  customer_id  store_id  quantity
0         1/1/1997  12/31/1996         869         3449         6         5
1         1/1/1997  12/31/1996        1472         3449         6         3
2         1/1/1997  12/28/1996          76         3449         6         4
3         1/1/1997  12/26/1996         320         3449         6         3
4         1/1/1997  12/25/1996           4         3449         6         4
		**sales2018**
  transaction_date  stock_date  product_id  customer_id  store_id  quantity
0         1/1/1998  12/25/1997           4         2439        10         3
1         1/1/1998  12/28/1997          11         4284        10         3
2         1/1/1998  12/28/1997          12          534        10         3
3         1/1/1998  12/29/1997          14         9743        10         2
4         1/1/1998  12/27/1997          16         3608        10         3
		**customers**
   customer_id  customer_acct_num first_name  last_name    customer_address  \
0            1        87462024688      Sheri     Nowmer    2433 Bailey Road
1            2        87470586299    Derrick    Whelply  2219 Dewing Avenue
2            3        87475757600     Jeanne      Derry     7640 First Ave.
3            4        87500482201    Michael     Spence       337 Tosca Way
4            5        87514054179       Maya  Gutierrez     8668 Via Neruda

  customer_city customer_state_province  customer_postal_code  \
0      Tlaxiaco                  Oaxaca                 15057
1         Sooke                      BC                 17172
2      Issaquah                      WA                 73980
3       Burnaby                      BC                 74674
4        Novato                      CA                 57355

  customer_country  birthdate marital_status yearly_income gender  \
0           Mexico  8/26/1961              M   $30K - $50K      F
1           Canada   7/3/1915              S   $70K - $90K      M
2              USA  6/21/1910              M   $50K - $70K      F
3           Canada  6/20/1969              M   $10K - $30K      M
4              USA  5/10/1951              S   $30K - $50K      F

   total_children  num_children_at_home            education acct_open_date  \
0               4                     2  Partial High School      9/10/1991
1               1                     0  Partial High School      3/11/1993
2               1                     1     Bachelors Degree      6/11/1991
3               4                     4  Partial High School      5/21/1994
4               3                     0      Partial College      8/21/1992

  member_card      occupation homeowner
0      Bronze  Skilled Manual         Y
1      Bronze    Professional         N
2      Bronze    Professional         Y
3      Normal  Skilled Manual         N
4      Silver          Manual         N
		**products**
   product_id product_brand                 product_name  product_sku  \
0           1    Washington       Washington Berry Juice  90748583674
1           2    Washington       Washington Mango Drink  96516502499
2           3    Washington  Washington Strawberry Drink  58427771925
3           4    Washington        Washington Cream Soda  64412155747
4           5    Washington         Washington Diet Soda  85561191439

   product_retail_price  product_cost  product_weight  recyclable  low_fat
0                  2.85          0.94            8.39         NaN      NaN
1                  0.74          0.26            7.42         NaN      1.0
2                  0.83          0.40           13.10         1.0      1.0
3                  3.64          1.64           10.60         1.0      NaN
4                  2.19          0.77            6.66         1.0      NaN
		**regions**
   region_id sales_district    sales_region
0          1  San Francisco    Central West
1          2    Mexico City  Mexico Central
2          3    Los Angeles      South West
3          4    Guadalajara     Mexico West
4          5      Vancouver     Canada West
		**returns**
  return_date  product_id  store_id  quantity
0    1/1/1997         250         6         1
1    1/1/1997         628         6         1
2    1/1/1997         869         6         1
3    1/2/1997         469        11         1
4    1/2/1997         532        23         2
		**stores**
   store_id  region_id           store_type store_name store_street_address  \
0         1         28          Supermarket    Store 1       2853 Bailey Rd
1         2         78        Small Grocery    Store 2   5203 Catanzaro Way
2         3         76          Supermarket    Store 3   1501 Ramsey Circle
3         4         27  Gourmet Supermarket    Store 4     433 St George Dr
4         5          4        Small Grocery    Store 5   1250 Coggins Drive

    store_city store_state store_country   store_phone first_opened_date  \
0     Acapulco    Guerrero        Mexico  262-555-5124          1/9/1982
1   Bellingham          WA           USA  605-555-8203          4/2/1970
2    Bremerton          WA           USA  509-555-1596         6/14/1959
3      Camacho   Zacatecas        Mexico  304-555-1474         9/27/1994
4  Guadalajara     Jalisco        Mexico  801-555-4324         9/18/1978

  last_remodel_date  total_sqft  grocery_sqft
0         12/5/1990       23593         17475
1          6/4/1973       28206         22271
2        11/19/1967       39696         24390
3         12/1/1995       23759         16844
4         6/29/1991       24597         15012

In [5]:
for key, df in tables.items():
    print(f"\t**{key}**:\n{df.columns.tolist()}")

	**sales2017**:
['transaction_date', 'stock_date', 'product_id', 'customer_id', 'store_id', 'quantity']
	**sales2018**:
['transaction_date', 'stock_date', 'product_id', 'customer_id', 'store_id', 'quantity']
	**customers**:
['customer_id', 'customer_acct_num', 'first_name', 'last_name', 'customer_address', 'customer_city', 'customer_state_province', 'customer_postal_code', 'customer_country', 'birthdate', 'marital_status', 'yearly_income', 'gender', 'total_children', 'num_children_at_home', 'education', 'acct_open_date', 'member_card', 'occupation', 'homeowner']
	**products**:
['product_id', 'product_brand', 'product_name', 'product_sku', 'product_retail_price', 'product_cost', 'product_weight', 'recyclable', 'low_fat']
	**regions**:
['region_id', 'sales_district', 'sales_region']
	**returns**:
['return_date', 'product_id', 'store_id', 'quantity']
	**stores**:
['store_id', 'region_id', 'store_type', 'store_name', 'store_street_address', 'store_city', 'store_state', 'store_country', 'store_phone', 'first_opened_date', 'last_remodel_date', 'total_sqft', 'grocery_sqft']

In [6]:
for key, df in tables.items():
    print(f"{key}: {df.shape}")

sales2017: (86837, 6)
sales2018: (182883, 6)
customers: (10281, 20)
products: (1560, 9)
regions: (109, 3)
returns: (7087, 4)
stores: (24, 13)

In [7]:
sales2017Copy = sales2017.copy().drop_duplicates()
sales2018Copy = sales2018.copy().drop_duplicates()
customersCopy = customers.copy().drop_duplicates()
productsCopy = products.copy().drop_duplicates()
regionsCopy = regions.copy().drop_duplicates()
returnsCopy = returns.copy().drop_duplicates()
storesCopy = stores.copy().drop_duplicates()

In [8]:
tablesCopy = {
    "sales2017" : sales2017Copy,
    "sales2018" : sales2018Copy,
    "customers" : customersCopy,
    "products" : productsCopy,
    "regions" : regionsCopy,
    "returns" : returnsCopy,
    "stores" : storesCopy
}

In [9]:
for key, df in tablesCopy.items():
    print(f"{key}: {df.shape}")

sales2017: (86836, 6)
sales2018: (182875, 6)
customers: (10281, 20)
products: (1560, 9)
regions: (109, 3)
returns: (7082, 4)
stores: (24, 13)

In [10]:
for key, df in tablesCopy.items():
    print(f"\t\t== {key}: {df.shape} ==")
    print(f"\n{df.info()}")

		== sales2017: (86836, 6) ==
<class 'pandas.DataFrame'>
Index: 86836 entries, 0 to 86836
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_date  86836 non-null  str
 1   stock_date        86836 non-null  str
 2   product_id        86836 non-null  int64
 3   customer_id       86836 non-null  int64
 4   store_id          86836 non-null  int64
 5   quantity          86836 non-null  int64
dtypes: int64(4), str(2)
memory usage: 6.1 MB

None
		== sales2018: (182875, 6) ==
<class 'pandas.DataFrame'>
Index: 182875 entries, 0 to 182882
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_date  182875 non-null  str
 1   stock_date        182875 non-null  str
 2   product_id        182875 non-null  int64
 3   customer_id       182875 non-null  int64
 4   store_id          182875 non-null  int64
 5   quantity          182875 non-null  int64
dtypes: int64(4), str(2)
memory usage: 12.9 MB

None
		== customers: (10281, 20) ==
<class 'pandas.DataFrame'>
RangeIndex: 10281 entries, 0 to 10280
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10281 non-null  int64
 1   customer_acct_num        10281 non-null  int64
 2   first_name               10281 non-null  str
 3   last_name                10280 non-null  str
 4   customer_address         10281 non-null  str
 5   customer_city            10281 non-null  str
 6   customer_state_province  10281 non-null  str
 7   customer_postal_code     10281 non-null  int64
 8   customer_country         10281 non-null  str
 9   birthdate                10281 non-null  str
 10  marital_status           10281 non-null  str
 11  yearly_income            10281 non-null  str
 12  gender                   10281 non-null  str
 13  total_children           10281 non-null  int64
 14  num_children_at_home     10281 non-null  int64
 15  education                10281 non-null  str
 16  acct_open_date           10281 non-null  str
 17  member_card              10281 non-null  str
 18  occupation               10281 non-null  str
 19  homeowner                10281 non-null  str
dtypes: int64(5), str(15)
memory usage: 2.7 MB

None
		== products: (1560, 9) ==
<class 'pandas.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            1560 non-null   int64
 1   product_brand         1560 non-null   str
 2   product_name          1560 non-null   str
 3   product_sku           1560 non-null   int64
 4   product_retail_price  1560 non-null   float64
 5   product_cost          1560 non-null   float64
 6   product_weight        1560 non-null   float64
 7   recyclable            873 non-null    float64
 8   low_fat               552 non-null    float64
dtypes: float64(5), int64(2), str(2)
memory usage: 155.4 KB

None
		== regions: (109, 3) ==
<class 'pandas.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region_id       109 non-null    int64
 1   sales_district  109 non-null    str
 2   sales_region    109 non-null    str
dtypes: int64(1), str(2)
memory usage: 4.8 KB

None
		== returns: (7082, 4) ==
<class 'pandas.DataFrame'>
Index: 7082 entries, 0 to 7086
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   return_date  7082 non-null   str
 1   product_id   7082 non-null   int64
 2   store_id     7082 non-null   int64
 3   quantity     7082 non-null   int64
dtypes: int64(3), str(1)
memory usage: 339.6 KB

None
		== stores: (24, 13) ==
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              24 non-null     int64
 1   region_id             24 non-null     int64
 2   store_type            24 non-null     str
 3   store_name            24 non-null     str
 4   store_street_address  24 non-null     str
 5   store_city            24 non-null     str
 6   store_state           24 non-null     str
 7   store_country         24 non-null     str
 8   store_phone           24 non-null     str
 9   first_opened_date     24 non-null     str
 10  last_remodel_date     24 non-null     str
 11  total_sqft            24 non-null     int64
 12  grocery_sqft          24 non-null     int64
dtypes: int64(4), str(9)
memory usage: 4.6 KB

None

In [11]:
sales2017Copy[["transaction_date", "stock_date"]] = sales2017Copy[["transaction_date", "stock_date"]].apply(pd.to_datetime)
sales2017Copy.info()

<class 'pandas.DataFrame'>
Index: 86836 entries, 0 to 86836
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_date  86836 non-null  datetime64[us]
 1   stock_date        86836 non-null  datetime64[us]
 2   product_id        86836 non-null  int64
 3   customer_id       86836 non-null  int64
 4   store_id          86836 non-null  int64
 5   quantity          86836 non-null  int64
dtypes: datetime64[us](2), int64(4)
memory usage: 4.6 MB

In [12]:
sales2018Copy[["transaction_date", "stock_date"]] = sales2018Copy[["transaction_date", "stock_date"]].apply(pd.to_datetime)
sales2018Copy.info()

<class 'pandas.DataFrame'>
Index: 182875 entries, 0 to 182882
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_date  182875 non-null  datetime64[us]
 1   stock_date        182875 non-null  datetime64[us]
 2   product_id        182875 non-null  int64
 3   customer_id       182875 non-null  int64
 4   store_id          182875 non-null  int64
 5   quantity          182875 non-null  int64
dtypes: datetime64[us](2), int64(4)
memory usage: 9.8 MB

In [13]:
customersCopy[["birthdate", "acct_open_date"]] = customersCopy[["birthdate", "acct_open_date"]].apply(pd.to_datetime)
customersCopy.info()

<class 'pandas.DataFrame'>
RangeIndex: 10281 entries, 0 to 10280
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10281 non-null  int64
 1   customer_acct_num        10281 non-null  int64
 2   first_name               10281 non-null  str
 3   last_name                10280 non-null  str
 4   customer_address         10281 non-null  str
 5   customer_city            10281 non-null  str
 6   customer_state_province  10281 non-null  str
 7   customer_postal_code     10281 non-null  int64
 8   customer_country         10281 non-null  str
 9   birthdate                10281 non-null  datetime64[us]
 10  marital_status           10281 non-null  str
 11  yearly_income            10281 non-null  str
 12  gender                   10281 non-null  str
 13  total_children           10281 non-null  int64
 14  num_children_at_home     10281 non-null  int64
 15  education                10281 non-null  str
 16  acct_open_date           10281 non-null  datetime64[us]
 17  member_card              10281 non-null  str
 18  occupation               10281 non-null  str
 19  homeowner                10281 non-null  str
dtypes: datetime64[us](2), int64(5), str(13)
memory usage: 2.5 MB

In [14]:
returnsCopy["return_date"] = pd.to_datetime(returnsCopy["return_date"])
returnsCopy.info()

<class 'pandas.DataFrame'>
Index: 7082 entries, 0 to 7086
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   return_date  7082 non-null   datetime64[us]
 1   product_id   7082 non-null   int64
 2   store_id     7082 non-null   int64
 3   quantity     7082 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 276.6 KB

In [15]:
storesCopy[["first_opened_date", "last_remodel_date"]] = storesCopy[["first_opened_date", "last_remodel_date"]].apply(pd.to_datetime)
storesCopy.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              24 non-null     int64
 1   region_id             24 non-null     int64
 2   store_type            24 non-null     str
 3   store_name            24 non-null     str
 4   store_street_address  24 non-null     str
 5   store_city            24 non-null     str
 6   store_state           24 non-null     str
 7   store_country         24 non-null     str
 8   store_phone           24 non-null     str
 9   first_opened_date     24 non-null     datetime64[us]
 10  last_remodel_date     24 non-null     datetime64[us]
 11  total_sqft            24 non-null     int64
 12  grocery_sqft          24 non-null     int64
dtypes: datetime64[us](2), int64(4), str(7)
memory usage: 4.2 KB

In [16]:
Sales = pd.concat([sales2017Copy, sales2018Copy]).drop_duplicates()

In [17]:
pd.DataFrame(Sales).head()

  transaction_date stock_date  product_id  customer_id  store_id  quantity
0       1997-01-01 1996-12-31         869         3449         6         5
1       1997-01-01 1996-12-31        1472         3449         6         3
2       1997-01-01 1996-12-28          76         3449         6         4
3       1997-01-01 1996-12-26         320         3449         6         3
4       1997-01-01 1996-12-25           4         3449         6         4

In [18]:
pd.DataFrame(customersCopy).head()

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
0,1,87462024688,Sheri,Nowmer,2433 Bailey Road,Tlaxiaco,Oaxaca,15057,Mexico,1961-08-26,M,$30K - $50K,F,4,2,Partial High School,1991-09-10,Bronze,Skilled Manual,Y
1,2,87470586299,Derrick,Whelply,2219 Dewing Avenue,Sooke,BC,17172,Canada,1915-07-03,S,$70K - $90K,M,1,0,Partial High School,1993-03-11,Bronze,Professional,N
2,3,87475757600,Jeanne,Derry,7640 First Ave.,Issaquah,WA,73980,USA,1910-06-21,M,$50K - $70K,F,1,1,Bachelors Degree,1991-06-11,Bronze,Professional,Y
3,4,87500482201,Michael,Spence,337 Tosca Way,Burnaby,BC,74674,Canada,1969-06-20,M,$10K - $30K,M,4,4,Partial High School,1994-05-21,Normal,Skilled Manual,N
4,5,87514054179,Maya,Gutierrez,8668 Via Neruda,Novato,CA,57355,USA,1951-05-10,S,$30K - $50K,F,3,0,Partial College,1992-08-21,Silver,Manual,N

In [19]:
customersCopy["customer_city"].value_counts()

customer_city
Richmond         191
Shawnee          111
Downey           110
Lebanon          108
Lemon Grove      107
                ...
Lakewood          82
La Cruz           78
Fremont           75
Santa Fe          51
San Francisco     47
Name: count, Length: 108, dtype: int64

In [20]:
customersCopy["customer_state_province"].value_counts()

customer_state_province
CA           4222
WA           2086
BC           1717
OR           1051
DF            347
Zacatecas     191
Guerrero      106
Jalisco       104
Yucatan        99
Mexico         97
Veracruz       93
Oaxaca         90
Sinaloa        78
Name: count, dtype: int64

In [21]:
customersCopy["customer_country"].value_counts()

customer_country
USA       7359
Canada    1717
Mexico    1205
Name: count, dtype: int64

In [22]:
pd.DataFrame(productsCopy).head()

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Washington,Washington Berry Juice,90748583674,2.85,0.94,8.39,NaN,NaN
1,2,Washington,Washington Mango Drink,96516502499,0.74,0.26,7.42,NaN,1.0
2,3,Washington,Washington Strawberry Drink,58427771925,0.83,0.40,13.10,1.0,1.0
3,4,Washington,Washington Cream Soda,64412155747,3.64,1.64,10.60,1.0,NaN
4,5,Washington,Washington Diet Soda,85561191439,2.19,0.77,6.66,1.0,NaN

In [23]:
productsCopy[["recyclable", "low_fat"]] = productsCopy[["recyclable", "low_fat"]].fillna(0).astype(int)

In [24]:
productsCopy.info()

<class 'pandas.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            1560 non-null   int64
 1   product_brand         1560 non-null   str
 2   product_name          1560 non-null   str
 3   product_sku           1560 non-null   int64
 4   product_retail_price  1560 non-null   float64
 5   product_cost          1560 non-null   float64
 6   product_weight        1560 non-null   float64
 7   recyclable            1560 non-null   int64
 8   low_fat               1560 non-null   int64
dtypes: float64(3), int64(4), str(2)
memory usage: 155.4 KB

In [25]:
regionsCopy.head()

   region_id sales_district    sales_region
0          1  San Francisco    Central West
1          2    Mexico City  Mexico Central
2          3    Los Angeles      South West
3          4    Guadalajara     Mexico West
4          5      Vancouver     Canada West

In [26]:
storesCopy.head()

,store_id,region_id,store_type,store_name,store_street_address,store_city,store_state,store_country,store_phone,first_opened_date,last_remodel_date,total_sqft,grocery_sqft
0,1,28,Supermarket,Store 1,2853 Bailey Rd,Acapulco,Guerrero,Mexico,262-555-5124,1982-01-09,1990-12-05,23593,17475
1,2,78,Small Grocery,Store 2,5203 Catanzaro Way,Bellingham,WA,USA,605-555-8203,1970-04-02,1973-06-04,28206,22271
2,3,76,Supermarket,Store 3,1501 Ramsey Circle,Bremerton,WA,USA,509-555-1596,1959-06-14,1967-11-19,39696,24390
3,4,27,Gourmet Supermarket,Store 4,433 St George Dr,Camacho,Zacatecas,Mexico,304-555-1474,1994-09-27,1995-12-01,23759,16844
4,5,4,Small Grocery,Store 5,1250 Coggins Drive,Guadalajara,Jalisco,Mexico,801-555-4324,1978-09-18,1991-06-29,24597,15012

In [27]:
cities = set(storesCopy["store_city"])

In [28]:
districts = set(regionsCopy["sales_district"])

In [29]:
print(len(cities))
print(len(districts))

23
22

In [30]:
print(cities - districts)
print(districts - cities)

{'Beverly Hills', 'San Andres', 'Merida'}
{'Tlaxiaco', 'Marida'}

In [31]:
regionsCopy["sales_district"] = regionsCopy["sales_district"].replace("Marida", "Merida")

In [33]:
DATA_PATH = "data"
Sales.to_parquet(os.path.join(DATA_PATH, "Sales.parquet"), index=False)
customersCopy.to_parquet(os.path.join(DATA_PATH, "customers.parquet"), index=False)
productsCopy.to_parquet(os.path.join(DATA_PATH, "products.parquet"), index=False)
regionsCopy.to_parquet(os.path.join(DATA_PATH, "regions.parquet"), index=False)
returnsCopy.to_parquet(os.path.join(DATA_PATH, "returns.parquet"), index=False)
storesCopy.to_parquet(os.path.join(DATA_PATH, "stores.parquet"), index=False)